In [8]:
import time 
import numpy as np

In [11]:
a = np.random.rand(1000000)
b = np.random.rand(1000000)

tic = time.time()
c = np.dot(a,b)
toc = time.time()

print(c)
print('vectorized version:' + str(1000*(toc-tic)) + 'ms')

c = 0
tic = time.time()
for i in range(1000000):
    c += a[i] * b[i]
toc = time.time()

print(c)
print('for loop:' + str(1000*(toc-tic)) + 'ms')

250416.37971248425
vectorized version:5.478143692016602ms
250416.3797124767
for loop:618.8929080963135ms


In [12]:
# brodcasting example

In [17]:
a = np.array([[12,14,16,18],
     [22,55,77,9],
     [2,4,6,8]])
print(a)

[[12 14 16 18]
 [22 55 77  9]
 [ 2  4  6  8]]


In [20]:
cal = a.sum(axis=0)
print(cal)

[36 73 99 35]


In [21]:
percentage = 100 * a/cal.reshape(1,4)
print(percentage)

[[33.33333333 19.17808219 16.16161616 51.42857143]
 [61.11111111 75.34246575 77.77777778 25.71428571]
 [ 5.55555556  5.47945205  6.06060606 22.85714286]]


In [22]:
# numpy vectors

In [23]:
a = np.random.randn(5)

In [24]:
print(a)

[-0.18524556 -0.93701131  0.13428154  1.45943365  0.07023347]


In [25]:
print(a.T)

[-0.18524556 -0.93701131  0.13428154  1.45943365  0.07023347]


In [30]:
tic = time.time() 
print(np.dot(a,a.T))
toc = time.time()

print('in ms:' + str(1000*(toc - tic)))

3.065216963527192
in ms:0.37407875061035156


In [31]:
k = a.T

In [32]:
k

array([-0.18524556, -0.93701131,  0.13428154,  1.45943365,  0.07023347])

In [33]:
tic = time.time() 
print(a * k)
toc = time.time()

print('in ms:' + str(1000*(toc - tic)))

[0.03431592 0.8779902  0.01803153 2.12994657 0.00493274]
in ms:1.9192695617675781
